Test add branch
LLazyEmail/nomoretogo_email_template pull request #283
Opened 2022-08-03 15:10 UTC by web4uartstudio

2022-08-03 15:35 UTC, atherdon commented
looks cool - give me please some code changes so i can merge it

2022-08-03 15:36 UTC, web4uartstudio commented
Я вроде как с нового листа но есть вопрос: 
какие задачи выполнять, что бы я не мешал и не вносил НЕ нужные корректировки ? @atherdon

2022-08-03 15:41 UTC, atherdon commented
все задачи которые я на вас закидывал видны тут: https://github.com/LLazyEmail/nomoretogo_email_template/issues/assigned/web4uartstudio

возможно часть мы уже сделали.

из быстрого и простого - попробывать заменить(потому что код не идеален, волнуют аттрибуты) часть нашего кода на компоненты из typography

2022-08-03 16:03 UTC, atherdon commented
небольшой upd - я начал генерировать полный темлпейт - скоро добьем!

текущая версия 

![image](https://user-images.githubusercontent.com/1469198/182655943-e54d2463-6369-478d-8887-ccd267db6407.png)



чтобы повторить - `yarn test:write`

2022-08-04 00:20 UTC, atherdon commented on src/components/instructionComponent.js
> +  return paragraph(content);
текущий компонент параграф который у нас в типографии отличается от того, который тут использовался - https://github.com/LLazyEmail/nomoretogo_email_template/blob/main/sub-modules/typography/src/components/paragraph.js

нужно сделать так чтобы мы могли слать разные аттрибуты. то что я и говорил

2022-08-04 00:21 UTC, atherdon commented on src/display/displayContent.js
> +export default 1; // result;
this line driving me crazy ))

2022-08-04 00:22 UTC, atherdon commented on sub-modules/innerTemplate/src/components/recipeComponent.js
> +  return paragraphComponent(content);
та же самая проблема с параграфом как и выще

2022-08-04 00:25 UTC, atherdon commented on sub-modules/outerTemplate/src/components/footerComponent.js
> -    return `<td align="center" width="24" style="padding: 0px 5px;" ng-show="slink.link != ''">
тут я запутался в наших махинациях - наверное вынесите мини компоненты в отдельный файл/файлы, потому что в длинном файле я путаюсь, когда делаю код ревью

2022-08-04 00:26 UTC, atherdon commented on sub-modules/outerTemplate/src/components/supportComponent.js
> +    attributes: `href="${href}" data-link-id="${id}"`,
стили теряются, похожая проблема на пагарраф выше

2022-08-04 00:27 UTC, atherdon commented on sub-modules/typography/src/components/image.js
> +    attributes: `href="${href}" data-link-id="${id}"`,
тут теряется аттрибут target

2022-08-04 00:29 UTC, atherdon requested changes
текущие компоненты image/paragraph/link не удовлетворяют нашим потребностям.
их нужно расширять чтобы все варианты одновременно работали.

похожую проблему я пытался решить в linkComponent

2022-08-04 11:44 UTC, web4uartstudio commented
> текущие компоненты image/paragraph/link не удовлетворяют нашим потребностям.

Это то о чем я говорил ранее - не будет универсальности. Универсальность будет только в обертке. Для примера "
ca6ad63" изменил paragraph. Жду комментарий или обсуждение @atherdon

2022-08-04 12:41 UTC, atherdon commented
передавайте разные аттрибуты, чтобы мы не теряли параметры. нам нужно использовать типографию и делать некоторые ващи унифицированно потому что иначе генератор просто не заработает.

лупасим - уже немного осталось

2022-08-04 12:42 UTC, atherdon commented
пулл посмотрю позже

2022-08-04 14:25 UTC, atherdon commented on src/components/instructionComponent.js
>    const content = { content: strong(title) };
выглядит хорошо!

2022-08-04 14:33 UTC, atherdon approved these changes

2022-08-04 14:35 UTC, merged

2022-08-04 14:44 UTC, atherdon commented
а можете отметить какие таски мы сделали этим пуллом? потому что я запутался

2022-08-04 14:44 UTC, atherdon commented
Плюс, залил свои изменения в main branch

2022-08-04 19:47 UTC, web4uartstudio commented
> а можете отметить какие таски мы сделали этим пуллом? потому что я запутался

226
250
248
246
256
243
241
238
236
234
231
229
227
@atherdon

2022-08-04 20:56 UTC, atherdon commented
дякую

2022-08-04 21:02 UTC, web4uartstudio commented
Я так понимаю что Вы из Харькова, что там у Вас, новости не очень (((((((
@atherdon

2022-08-04 22:25 UTC, atherdon commented
Да, обстрел был очень близко к дому где у меня компьютер. А через пол часа
после обстрела у меня как раз звонок был в startup school.
Ну и сейчас тревога и пишу из ванной комнаты

On Fri, Aug 5, 2022, 12:02 AM web4uartstudio ***@***.***>
wrote:

> Я так понимаю что Вы из Харькова, что там у Вас, новости не очень (((((((
> @atherdon <https://github.com/atherdon>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LLazyEmail/nomoretogo_email_template/pull/283#issuecomment-1205764432>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALGWDTXPN47D54BPMQCWCLVXQVXHANCNFSM55PHGAOQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>